give @s ct:air_block 1
give @s ct:block_copy 1
give @s ct:click_tp 1
give @s ct:debug_kill 1
give @s ct:gm_changer 1
give @s ct:kill_enemy 1
give @s ct:protect_player 1
give @s ct:set_level 1
give @s ct:time_changer 1