give @s command_block 1
give @s chain_command_block 1
give @s repeating_command_block 1
give @s barrier 1
give @s structure_block 1
give @s structure_void 1
give @s light_block_15 1
give @s allow 1
give @s deny 1